# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master
name: $(Date:yyyyMMdd)$(Rev:.r)
stages:
- stage: One
  jobs:
  - job: "Build"
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          sleep 30

- stage: Two
  jobs:
  - job: 'PushArtifacts'
    pool: server
    steps:
    - task: InvokeRESTAPI@1
      inputs:
        connectionType: 'connectedServiceName'
        serviceConnection: 'ado118'
        method: 'POST'
        body: |
          {
            "artifacts": [
              {
                "name": "balu-Artifact1",
                "version": "1.$(build.buildId)",
                "semanticVersion": "1.$(build.buildId).0",
                "repositoryName": "balu-ArtifactRepo1"
              },
              {
                "name": "balu-Artifact2",
                "version": "1.$(build.buildId)",
                "semanticVersion": "1.$(build.buildId).0",
                "repositoryName": "balu-ArtifactRepo1"
              }
            ],
          "pipelineName": "$(system.teamProject)/$(build.definitionName)",
          "taskExecutionNumber": "$(build.buildId)",
          "stageName": "$(system.jobDisplayName)",
          "branchName": "$(build.sourceBranchName)"
          }
        urlSuffix: '/artifact/registration?orchestrationToolId=8ceb7d6adbe6141056ebb12c4e961920'
        waitForCompletion: 'false'


  - job: 'RegisterArtifactPackage'
    pool: server
    
    steps:
    - task: InvokeRESTAPI@1
      inputs:
        connectionType: 'connectedServiceName'
        serviceConnection: 'ado118'
        method: 'POST'
        body: |
          {
            "name": "balu-ArtifactPackage1",
            "artifacts": [
              {
                "name": "balu-Artifact1",
                "repositoryName": "balu-ArtifactRepo1",
                "version": "1.$(build.buildId)"
              },
              {
                "name": "balu-Artifact2",
                "repositoryName": "balu-ArtifactRepo1",
                "version": "1.$(build.buildId)"
              }
            ],
            "pipelineName": "$(system.teamProject)/$(build.definitionName)",
            "taskExecutionNumber": "$(build.buildId)",
            "stageName": "$(system.jobDisplayName)",
            "branchName": "$(build.sourceBranchName)"
          }
        urlSuffix: '/package/registration?orchestrationToolId=8ceb7d6adbe6141056ebb12c4e961920'
        waitForCompletion: 'false'

    - task: Delay@1
      inputs:
            delayForMinutes: '1'

- stage: Three
  jobs:
  - job: 'Deploy'
    pool: server
    steps:
    - task: InvokeRESTAPI@1
      inputs:
        connectionType: 'connectedServiceName'
        serviceConnection: 'ado118'
        method: 'POST'
        body: |
          {
              "buildNumber": "$(build.buildId)",
              "isMultiBranch": "true",
              "branchName": "$(build.sourceBranchName)"
          }
        urlSuffix: '/orchestration/changeControl?toolId=8ceb7d6adbe6141056ebb12c4e961920'
        waitForCompletion: 'true'
  

