# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- QA
name: $(Date:yyyyMMdd)$(Rev:.r)
stages:
- stage: Build
  jobs:
  - job: "Build"
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here1
- stage: Test
  jobs:
  - job: "Test"
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'test'
        testRunTitle: 'Test'
      continueOnError: true
- stage: Deploy
  jobs:
  - job: "log"
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          echo "log inprogres"
  - job: "Deploy"
    dependsOn: 'log'
    pool: server
    steps:
    - task: InvokeRESTAPI@1
      inputs:
        connectionType: 'connectedServiceName'
        serviceConnection: 'bmurkiparis'
        method: 'POST'
        body: |
         {
            "buildNumber": "$(build.buildId)",
            "isMultiBranch": "true",
            "branchName": "$(build.sourceBranchName)"
                   }
        waitForCompletion: 'true'

